server:
  port: 8888
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  config: classpath:logback-spring.xml

cors:
  allow: true

